# Generated by Django 4.2.1 on 2023-05-11 02:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.IntegerField()),
                ('latest_action', jsonfield.fields.JSONField()),
                ('number', models.CharField(max_length=10)),
                ('chamber', models.CharField(max_length=20)),
                ('chamber_code', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=5)),
                ('update_date', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
